data <- read.table("household_power_consumption.txt", sep = ";", na.strings = "?", skip = 66637 , nrows = 2881)
head <- read.table("household_power_consumption.txt", sep = ";", na.strings = "?", nrows = 1)
ndate <- strptime(paste(data[,1], data[,2]), "%d/%m/%Y %H:%M:%S", tz="UTC")
ndata <- cbind(ndate, data[,3:9])
colnames(ndata)<-c("Date/Time", sapply(head[,3:9], toString))
par(mfrow=c(2,2))
plot(ndata[,1], ndata[,2], type ="l", xlab = "", ylab = "Active Global Power")
plot(ndata[,1], ndata[,4], type = "l", xlab = "datetime", ylab = "Voltage")
plot(ndata[,1], ndata[,6], type ="l", xlab = "", ylab = "Energy sub metering")
lines(ndata[,1], ndata[,7], col = "red")
lines(ndata[,1], ndata[,8], col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1, col = c("black", "red", "blue"), bty = "n", cex = 0.7, x.intersp = 2.2, adj = 0.2)
plot(ndata[,1], ndata[,3], type ="l", xlab = "datetime", ylab = "Global_reactive_power")
dev.copy(png, file = "plot4.png")
dev.off()